name: Update source data

on:
#  schedule:
#    - cron: '0 0,12 * * *'
  # Hook to trigger a manual run. 
  # See: https://goobar.io/2019/12/07/manually-trigger-a-github-actions-workflow/
  # A sample request looks like: 
  # curl https://api.github.com/repos/covid-projections/covid-data-public/dispatches -H "Authorization: token $AUTH_TOKEN" -H "Accept: application/vnd.github.everest-preview+json" -X POST -d '{"event_type": "update-source-data"}'
  repository_dispatch:
    types: update-source-data
# To debug, comment out above schedule, and uncomment the stanza below.
# Fill in your own branch name, and each push will trigger a run
  push:
    branches:
    - tgb-workflow-pyversion-notify

jobs:
  update-source-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: tgb-workflow-pyversion-notify
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.6'
        architecture: 'x64'
    - name: Cache Pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Update Datasets
      run: ./update.sh
    - name: Create Update Commit
      run: ./push_update.sh
    - name: Slack notification
      if: always() # Pick up events even if the job fails or is canceled.
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: eng
        STATUS: ${{job.status}}
      uses: Ilshidur/action-slack@fb92a78
      with:
        args: 'Update Datasets in covid-data-public repo notify, to eng! Job status: {{STATUS}}'
        
